server:
  port: 8000

spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cl6-1-finalproject.cdqf0gxh6nhf.ap-northeast-2.rds.amazonaws.com:3306/test1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: Ghdwlsguq1!

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true